FROM nvidia/cuda:12.0.0-cudnn8-devel-ubuntu20.04

ARG TORCH_CUDA_ARCH_LIST="7.5"
ARG env=production
ARG DEBIAN_FRONTEND=noninteractive

# Use the Korean official mirror in non-production environments
RUN if [ ${env} != "production" ]; then \
    cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
    sed -i s%http://deb.debian.org/debian%http://ftp.kr.debian.org/debian% /etc/apt/sources.list; \
    fi

RUN apt-get update && \
    apt-get -y install libaio1 wget unzip python3.8 python3.8-dev python3-pip libgl1-mesa-glx libglib2.0-0 && \
    python3.8 -m pip install pip --upgrade && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /super-global/requirements.txt

WORKDIR /super-global

# Install related packages
RUN pip install -r requirements.txt

# Install pytorch
# RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
